# Generated by Django 3.2 on 2021-04-21 20:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Farms',
            new_name='Farm',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='farms',
            new_name='farm',
        ),
        migrations.RenameField(
            model_name='telephone',
            old_name='farms',
            new_name='farm',
        ),
    ]
